# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_professor_professorcourse_teachingassistant_teachingassistantcourse'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Tutor')),
            ],
        ),
    ]
