# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursecomment_professorcomment'),
        ('students', '0002_mycourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Subject'),
        ),
    ]
