# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('studentLink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('skillRating', models.PositiveSmallIntegerField()),
                ('moneyRating', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
