# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 01:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillRating', models.PositiveSmallIntegerField(default=0)),
                ('moneyRating', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('studentLink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tutor_name', models.CharField(default='John Doe', max_length=256)),
                ('skillRating', models.PositiveSmallIntegerField(default=0)),
                ('moneyRating', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Tutor'),
        ),
    ]
