# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_mycourse_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourse',
            name='subject',
        ),
    ]
