# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursesection'),
        ('courses', '0002_auto_20170407_0107'),
    ]

    operations = [
    ]
