# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_filelinker'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelinker',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkCourse', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='filelinker',
            name='infoLink',
            field=models.URLField(),
        ),
    ]
