# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170425_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filelinker',
            old_name='description',
            new_name='notes',
        ),
    ]
