# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170407_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('office', models.CharField(max_length=250)),
                ('office_hours', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('office', models.CharField(max_length=250)),
                ('office_hours', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssistantCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('teaching_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.TeachingAssistant')),
            ],
        ),
    ]
