# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_merge_20170407_0200'),
        ('courses', '0005_professor_professorcourse_teachingassistant_teachingassistantcourse'),
    ]

    operations = [
    ]
